-- Generated from generator/demo_specs/aws-philippines-remittance-digital-wallet.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-remittance-digital-wallet
-- This is the schema that is actually deployed for PH_REMITTANCE_DIGITAL_WALLET.

-- Alerts fire on the bottom tail of Avg Balance
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_BALANCE) AS T
  FROM RAW.TRANSACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_BALANCE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_BALANCE), 2) AS AVG_BALANCE
FROM RAW.TRANSACTIONS f
JOIN RAW.FRAUD_CASES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_BALANCE), 2) AS AVG_BALANCE
FROM RAW.TRANSACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_BALANCE) AS KPI_AVG_BALANCE FROM RAW.TRANSACTIONS),
     en AS (SELECT SUM(KPI_WALLET_USERS) AS KPI_WALLET_USERS, SUM(KPI_MONTHLY_ACTIVE) AS KPI_MONTHLY_ACTIVE, SUM(KPI_TRANSACTIONS_MTD) AS KPI_TRANSACTIONS_MTD, SUM(KPI_P2P_TRANSFERS) AS KPI_P2P_TRANSFERS, SUM(KPI_BILL_PAYMENTS) AS KPI_BILL_PAYMENTS, SUM(KPI_MERCHANT_SPEND) AS KPI_MERCHANT_SPEND FROM RAW.FRAUD_CASES)
  SELECT 1 AS SORT_ORDER, 'Wallet Users' AS TITLE, KPI_WALLET_USERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_WALLET_USERS) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Monthly Active' AS TITLE, KPI_MONTHLY_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_MONTHLY_ACTIVE) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Balance' AS TITLE, KPI_AVG_BALANCE AS VALUE_NUM, '₱' || LTRIM(TO_VARCHAR(CAST(ROUND((KPI_AVG_BALANCE)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Transactions (MTD)' AS TITLE, KPI_TRANSACTIONS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_TRANSACTIONS_MTD) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'P2P Transfers' AS TITLE, KPI_P2P_TRANSFERS AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_P2P_TRANSFERS) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Bill Payments' AS TITLE, KPI_BILL_PAYMENTS AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_BILL_PAYMENTS) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Merchant Spend' AS TITLE, KPI_MERCHANT_SPEND AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_MERCHANT_SPEND) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
