-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Digital Wallet & Payments Hub Analytics
-- ============================================================================
USE DATABASE DIGITAL_WALLET;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: FRAUD_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.FRAUD_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FRAUD_TIMESERIES'),
  SERIES_COLNAME => 'TXN_TYPE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'FRAUD_RATE',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.FRAUD_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.FRAUD_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FRAUD_TIMESERIES'), SERIES_COLNAME => 'TXN_TYPE', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'FRAUD_RATE'));

-- ML.CLASSIFICATION: FRAUD_RISK_CLASSIFIER
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.FRAUD_RISK_CLASSIFIER(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TRANSACTION_VELOCITY'),
  TARGET_COLNAME => 'IS_FRAUD'
);

