-- ============================================================================
-- 99_RESET.SQL — Reset Digital Wallet & Payments Hub Analytics to clean demo state
-- ============================================================================
USE DATABASE DIGITAL_WALLET;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_STREAM_TRANSACTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_FRAUD SUSPEND;
ALTER TASK IF EXISTS APP.TASK_ALERT_RISK SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.TRANSACTION_VELOCITY REFRESH;
ALTER DYNAMIC TABLE CURATED.MERCHANT_RISK_PROFILE REFRESH;
ALTER DYNAMIC TABLE CURATED.ECOSYSTEM_HEALTH REFRESH;
ALTER DYNAMIC TABLE CURATED.FRAUD_TIMESERIES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM DIGITAL_WALLET.RAW.TRANSACTIONS → 18000000
-- SELECT COUNT(*) FROM DIGITAL_WALLET.RAW.WALLET_ACCOUNTS → 4500000
-- SELECT COUNT(*) FROM DIGITAL_WALLET.RAW.MERCHANTS → 125000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_ALERT_RISK RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_FRAUD RESUME;
ALTER TASK IF EXISTS APP.TASK_STREAM_TRANSACTIONS RESUME;
